[package]
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]
name = "tabin-plugins"
version = "0.1.4"

[dependencies]
bitflags = "*"
chrono = "0.2"
docopt = "0.6"
hyper = "0.6"
itertools = "0.4"
lazy_static = "0.1"
libc = "0.1.12"
nix = "^0.4.2"
regex = "0.1"
rustc-serialize = "0.3"
scan_fmt = "0.1"
url = "0.2"
wrapped_enum = "0.1"

[dependencies.clap]
default-features = false
features = ["suggestions"]
version = "1.3"
