[package]
name = "turbine"
version = "0.0.1"
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]

[dependencies]
hyper = "0.5.0"
clap = "*"
chrono = "0.2"
clippy = "*"
rustc-serialize = "0.3"
url = "0.2"
docopt = "0.6"
