[package]
name = "turbine"
version = "0.0.1"
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]

[dependencies]
hyper = "0.6"
chrono = "0.2"
rustc-serialize = "0.3"
url = "0.2"

[dependencies.turbine-plugins]
path = "turbine-plugins"

[dev-dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"
